cost-analyzer:
  serviceAccount:
    create: false
  global:
    grafana:
      enabled: false
      proxy: false
  prometheus:
    configmapReload:
      prometheus:
        ## If false, the configmap-reload container will not be deployed
        ##
        enabled: false
    kube-state-metrics:
      disabled: true
    nodeExporter:
      enabled: false