cost-analyzer:
  podSecurityPolicy:
    enabled: false
  kubecostModel:
    fullImageName: null
  kubecostFrontend:
    fullImageName: null
  serviceAccount:
    create: false
  global:
    grafana:
      enabled: null
      proxy: null
  prometheus:
    server:
      image:
        repository: null
        tag: null
    serviceAccounts:
      server:
        create: false
    configmapReload:
      prometheus:
        ## If false, the configmap-reload container will not be deployed
        ##
        enabled: false
    kube-state-metrics:
      disabled: true
    nodeExporter:
      enabled: false
  reportingSecret: ""
    # rbac:
    #   create: false